name: alumni_tracker
description: Starter project pelacakan alumni
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter